### ISSUE TITLE
[SR - task] Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by Scarlett0JS** [Scarlett0JS/Todo-App-React#1]
### 기능

- [ ] Todo 생성
   - [ ] Input창에 할일을 적고 생성 버튼을 누르면 할일이 추가된다.
- [ ] Todo 체크
   - [ ] 추가된 할일 옆 체크박스를 클릭하면 완료로 체크 된다.
- [ ] Todo 삭제
   - [ ] 추가된 할일 옆 삭제 버튼을 누르면 삭제 된다.

### 프레임워크 설치
- Redux
- Styled-Component
- ESLint, Prettier

### 예상 작업 시간
- 3~4h
